//! US5 — http handler execution through the full dispatch pipeline.
//!
//! Uses a minimal `std::net::TcpListener` stub server to exercise the blocking
//! POST path end-to-end:
//!
//! * A 2xx response body parsed as CC JSON flows through
//!   `command_outcome_to_decision` → `merge_decisions` → `emit_decision`, and
//!   a `permissionDecision:"deny"` body surfaces as a Cursor deny at exit 0.
//!
//! * A connection-refused URL (closed port) → `run_http_handler` returns a
//!   non-blocking `HandlerOutcome` → fail-open allow (empty stdout, exit 0).
//!
//! The stub server accepts exactly one connection, reads past the HTTP request
//! headers, and sends a canned HTTP 200 response. It is intentionally minimal —
//! no TLS, no keep-alive — to keep test latency low and avoid any external
//! network dependency.

use std::io::{Read, Write};

use tome::commands::harness::run_hook;
use tome::harness::hooks_ir::HookManifest;

// --- Helpers -----------------------------------------------------------------

/// Deserialise a `HookManifest` from a JSON literal (panics on bad input —
/// acceptable for test set-up code).
fn manifest(json: &str) -> HookManifest {
    serde_json::from_str(json).expect("parse manifest JSON")
}

/// Build a manifest with a single `PreToolUse` http handler pointing at `url`.
fn manifest_for_url(url: &str) -> HookManifest {
    // timeout_ms: 5000 keeps the test bounded even if TCP state is unexpectedly
    // slow; the normal path resolves in <100 ms.
    let json = format!(
        r#"{{
            "harness": "cursor",
            "events": {{
                "PreToolUse": [
                    {{
                        "plugin": "cat:webhook",
                        "timeout_ms": 5000,
                        "handler": {{ "type": "http", "url": "{url}" }}
                    }}
                ]
            }}
        }}"#
    );
    manifest(&json)
}

/// Spawn a single-accept stub HTTP server on a random loopback port.
///
/// Returns `(port, join_handle)`. The server thread accepts one TCP connection,
/// drains enough of the request to unblock the writer, then sends a canned
/// HTTP 200 response and closes the connection.
fn start_stub_server(response_body: &str) -> (u16, std::thread::JoinHandle<()>) {
    let listener = std::net::TcpListener::bind("127.0.0.1:0").expect("bind stub server");
    let port = listener.local_addr().expect("local_addr").port();
    let body = response_body.to_owned();
    let handle = std::thread::spawn(move || {
        // Accept one connection (the test sends exactly one request).
        if let Ok((mut stream, _)) = listener.accept() {
            // Drain the HTTP request (headers + body).  A 4 KiB read covers the
            // CC JSON body generated by the dispatcher; more would require a
            // full HTTP parser (unnecessary here).
            let mut buf = vec![0u8; 4096];
            let _ = stream.read(&mut buf);
            let response = format!(
                "HTTP/1.1 200 OK\r\nContent-Type: application/json\r\nContent-Length: {}\r\nConnection: close\r\n\r\n{}",
                body.len(),
                body
            );
            let _ = stream.write_all(response.as_bytes());
            // `stream` drops here → FIN sent → reqwest sees EOF after the body.
        }
    });
    (port, handle)
}

/// Bind a listener to get a random port, then immediately close it.
/// Returns the port number — connecting to it will be refused.
fn closed_port() -> u16 {
    let l = std::net::TcpListener::bind("127.0.0.1:0").expect("bind for closed port");
    let port = l.local_addr().expect("local_addr").port();
    drop(l); // port is now closed; next TCP connect attempt → RST
    port
}

// --- Tests -------------------------------------------------------------------

/// An http hook whose server returns a 2xx body with `permissionDecision:"deny"`
/// is parsed through the CC pipeline and emitted as a Cursor deny at exit 0.
///
/// This pins the full path: stub server → `run_http_handler` →
/// `command_outcome_to_decision` → `merge_decisions` → `emit_decision`
/// (Cursor wire, snake_case, exit 0).
#[test]
fn http_handler_deny_from_2xx_body() {
    let canned = r#"{"hookSpecificOutput":{"permissionDecision":"deny","permissionDecisionReason":"http says no"}}"#;
    let (port, server) = start_stub_server(canned);
    let url = format!("http://127.0.0.1:{port}");

    let m = manifest_for_url(&url);
    let out = run_hook::dispatch_core("cursor", "PreToolUse", r#"{"tool_name":"Bash"}"#, Some(&m));

    // Join the server thread so any internal panic surfaces in the test.
    let _ = server.join();

    // Cursor blocks via JSON (snake_case `permission:"deny"`), never exit 2.
    assert_eq!(out.exit_code, 0, "Cursor deny must be exit 0");
    assert!(
        out.stdout.contains("\"permission\":\"deny\""),
        "expected cursor deny JSON, got: {}",
        out.stdout
    );
    assert!(
        out.stdout.contains("http says no"),
        "expected the deny reason from the HTTP body, got: {}",
        out.stdout
    );
}

/// A connection-refused URL (the listener is closed before dispatch) causes a
/// transport error that is treated as a fail-open non-blocking allow.
///
/// This pins the fail-open guarantee: `run_http_handler` returns exit 0 +
/// empty stdout on transport error, `command_outcome_to_decision` maps that to
/// `CcDecision::default()`, and the Cursor emitter emits empty stdout + exit 0.
#[test]
fn http_handler_conn_refused_is_fail_open() {
    let port = closed_port();
    let url = format!("http://127.0.0.1:{port}");

    // timeout_ms: 2000 so the test is bounded even if RST takes an extra RTT.
    let m = manifest(&format!(
        r#"{{
                "harness": "cursor",
                "events": {{
                    "PreToolUse": [
                        {{
                            "plugin": "cat:webhook",
                            "timeout_ms": 2000,
                            "handler": {{ "type": "http", "url": "{url}" }}
                        }}
                    ]
                }}
            }}"#
    ));
    let out = run_hook::dispatch_core("cursor", "PreToolUse", r#"{"tool_name":"Bash"}"#, Some(&m));

    assert_eq!(
        out.exit_code, 0,
        "conn-refused must fail open at exit 0, not block the agent"
    );
    assert!(
        out.stdout.is_empty(),
        "conn-refused must be a non-blocking allow (empty stdout), got: {}",
        out.stdout
    );
}
